### ISSUE TITLE
Consts.js should contain provider and VM type configuration

### ISSUE THREAD

**Issue by ejj** [kklin/arvados#2]
(Note or alternatively we should use base infrastructure, or some new thing that's better than it).

**Comment by kklin** [comment]
Pulled the configuration out in https://github.com/kklin/arvados/commit/88b326b814edf807a9735ee343ec2961974e0e24.

Once we decide on what to do about base infrastructure we can revisit this. Feel free to reopen this @ejj if you'd like to keep it open.
